import {
  ChartColumn,
  CircleHelp,
  ContactRound,
  FileImage,
  FileText,
  GraduationCap,
  History,
  Home,
  Images,
  LayoutDashboard,
  Medal,
  MessageSquareQuote,
  Navigation,
  Settings2,
  ShieldQuestion,
  Sparkles,
} from "lucide-react"

export const adminNavItems = [
  { title: "Dashboard", href: "/admin", icon: LayoutDashboard },
  { title: "Site Settings", href: "/admin/site-settings", icon: Settings2 },
  { title: "Navigation", href: "/admin/navigation", icon: Navigation },
  { title: "Homepage", href: "/admin/homepage", icon: Home },
  { title: "News", href: "/admin/news", icon: FileText },
  { title: "Partners & Accreditation", href: "/admin/partners-accreditation", icon: Medal },
  { title: "History Timeline", href: "/admin/history-timeline", icon: History },
  { title: "Why Choose Us", href: "/admin/why-choose-us", icon: Sparkles },
  { title: "Education Programs", href: "/admin/education-programs", icon: GraduationCap },
  { title: "Facilities", href: "/admin/facilities", icon: ShieldQuestion },
  { title: "Gallery", href: "/admin/gallery", icon: Images },
  { title: "FAQ", href: "/admin/faq", icon: CircleHelp },
  { title: "Testimonials", href: "/admin/testimonials", icon: MessageSquareQuote },
  { title: "Profile Page", href: "/admin/profile-page", icon: ChartColumn },
  { title: "Contact Page", href: "/admin/contact-page", icon: ContactRound },
  { title: "Footer", href: "/admin/footer", icon: FileImage },
  { title: "Media Library", href: "/admin/media-library", icon: FileImage },
] as const
