import {
  Baby,
  BookOpen,
  BookOpenCheck,
  BookText,
  BriefcaseMedical,
  Building2,
  Camera,
  ChartColumn,
  CircleHelp,
  FileText,
  FolderOpen,
  GraduationCap,
  HandHelping,
  HeartHandshake,
  Languages,
  Landmark,
  LayoutDashboard,
  ListTree,
  Mail,
  MapPin,
  Medal,
  MessageCircle,
  Phone,
  Play,
  Rabbit,
  School,
  Settings2,
  ShieldCheck,
  Sparkles,
  Star,
  SwatchBook,
  Waves,
  type LucideIcon,
} from "lucide-react"

export const iconOptions = [
  ["book-open", BookOpen],
  ["book-open-check", BookOpenCheck],
  ["book-text", BookText],
  ["briefcase-medical", BriefcaseMedical],
  ["building-2", Building2],
  ["camera", Camera],
  ["chart-column", ChartColumn],
  ["child", Baby],
  ["circle-help", CircleHelp],
  ["file-text", FileText],
  ["folder-open", FolderOpen],
  ["graduation-cap", GraduationCap],
  ["hand-helping", HandHelping],
  ["heart-handshake", HeartHandshake],
  ["horse", Rabbit],
  ["languages", Languages],
  ["landmark", Landmark],
  ["layout-dashboard", LayoutDashboard],
  ["list-tree", ListTree],
  ["mail", Mail],
  ["map-pin", MapPin],
  ["medal", Medal],
  ["message-circle", MessageCircle],
  ["phone", Phone],
  ["play", Play],
  ["school", School],
  ["settings-2", Settings2],
  ["shield-check", ShieldCheck],
  ["sparkles", Sparkles],
  ["star", Star],
  ["swatch-book", SwatchBook],
  ["waves", Waves],
] as const satisfies ReadonlyArray<readonly [string, LucideIcon]>

const iconMap = Object.fromEntries(iconOptions) as Record<string, LucideIcon>

export function getIconComponent(key: string) {
  return iconMap[key] ?? Sparkles
}
